# Stats 21 - HW 3

# Zachary Fann

Homework copyright Miles Chen. Problems have been adapted from the exercises in Think Python 2nd Ed by Allen B. Downey.

The questions have been entered into this document. You will modify the document by entering your code.

Make sure you run the cell so the requested output is visible. Export it as an HTML file and then print to PDF.

**Homework is an opportunity to practice coding and to practice problem solving.**

**Doing exercises is where you will do most of your learning.**

**Using AI or copying someone else's solutions takes away your learning opportunities. It is also academic dishonesty.**

## Reading

- Chapter 10 - Dictionaries
- Chapter 12 - Tuples
- Chapter 13 - Files

Please keep up with the reading. The chapters are short.

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.1

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

Write a function that reads the words in `words.txt` and stores them as keys in a dictionary. It doesn't matter what the values are. Then you can use the `in` operator as a fast way to check whether a string is in the dictionary.

In [1]:
def make_word_dict():
    d = dict()
    for line in open('words.txt'):
        word = line.strip()
        d[word] = "1"
    return d
word_dict = make_word_dict()

In [2]:

"hello" in word_dict

True

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.4

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

In HW2 Exercise 10.7, you created a function called `has_duplicates()`. It takes a list as a parameter and returns `True` if there is any object that appears more than once in the list.

Use a dictionary to write a faster, simpler version of `has_duplicates()`.

In [3]:
def has_duplicates(t):
    d = dict()
    for item in t:
        if item in d:
            return True
        else:
            d[item] = "1"
    return False
    

In [4]:
has_duplicates(['a','b','b','c'])

True

In [5]:
has_duplicates(['a','b','c','a'])

True

### Modified Exercise based on Think Python 2ed. Chap 11, Section 10, Exercise 11.5

<https://greenteapress.com/thinkpython2/html/thinkpython2012.html>

A Caesar cipher is a weak form of encryption that involves 'rotating' each letter by a fixed number of places. To rotate a letter means to shift it through the alphabet, wrapping around to the beginning if necessary. "A" rotated by 3 is "D". "Z" rotated by 1 is "A".

Two words are "rotate pairs" if you can rotate one of them and get the other. For example, "cheer" rotated by 7 is "jolly".

Write a script that reads in the wordlist `words.txt` and finds all the rotate pairs of words that are 5 letters or longer.

One function that could be helpful is the function `ord()` which converts a character to a numeric code. Keep in mind that numeric codes for uppercase and lowercase letters are different.

Some hints:

- you can write helper functions, such as a function that will rotate a letter by a certain number and/or another function that will rotate a word by a number of letters
- to keep your script running quickly, you should use the wordlist dictionary from exercise 11.1

In [6]:
# write your code here.

def rotate(word, n):
    new_word = ""
    for i in range(len(word)):
        new_word += chr(ord(word[i]) + n)
    return new_word

for line in open('words.txt'):
    word = line.strip()
    if len(word) >= 5:
        for n in range(1, 26):
            new_word = rotate(word, n)
            if new_word in word_dict:
                print(word, new_word)
   

adder beefs
anteed bouffe
banjo ferns
biffs holly
bolls hurry
chain ingot
cheer jolly
danio herms
eches kinky
fadge torus
fills lorry
ganja kerne
golem murks
inkier purply
jiffs polly
jinni potto
jinns potty
johns punty
lallan pepper
lutea pyxie
mills sorry
mocha suing
molas surgy
noggs tummy
pecan tiger
primero sulphur
ratan vexer
sheer tiffs
sneer toffs
steeds tuffet
steer tuffs
teloi whorl


### Modified Exercise based on Think Python 2ed. Chap 12, Section 10, Exercise 12.2

<https://greenteapress.com/thinkpython2/html/thinkpython2013.html>

Write a program that reads a word list from a file (see Section 9.1) and finds all the sets of words that are anagrams.

After finding all anagram sets, print the list of all anagram sets that have 6 or more entries in it.

Here is an example of what the output might look like:

~~~
['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']
['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced']
...
~~~

Hint:

First traverse the entire wordlist to build a dictionary that maps from a collection of letters to a list of words that can be spelled with those letters. The question is, how can you represent the collection of letters in a way that can be used as a key? i.e. The word "eat" and the word "tea" should be in a list associated with a key ('a','e','t').

In [7]:
def sortWord(word):
    return ''.join(sorted(word))
ana = dict()
for line in open('words.txt'):
    word = line.strip()
    if sortWord(word) in ana.keys():
        ana[sortWord(word)] = ana[sortWord(word)] + ", " + word
    else:
        ana[sortWord(word)] = word

for key in ana:
    if ana[key].count(",") >= 5:
        print(ana[key])

        

abets, baste, bates, beast, beats, betas, tabes
acers, acres, cares, carse, escar, races, scare, serac
acred, arced, cadre, cared, cedar, raced
aiders, deairs, irades, raised, redias, resaid
airts, astir, sitar, stair, stria, tarsi
alert, alter, artel, later, ratel, taler
alerting, altering, integral, relating, tanglier, triangle
alerts, alters, artels, estral, laster, ratels, salter, slater, staler, stelar, talers
alevin, alvine, valine, veinal, venial, vineal
algins, aligns, lasing, liangs, ligans, lingas, signal
aliens, alines, elains, lianes, saline, silane
aligners, engrails, nargiles, realigns, signaler, slangier
amens, manes, manse, means, mensa, names, nemas
anestri, nastier, ratines, retains, retinas, retsina, stainer, stearin
angriest, astringe, ganister, gantries, granites, ingrates, rangiest
apers, asper, pares, parse, pears, prase, presa, rapes, reaps, spare, spear
ardeb, barde, bared, beard, bread, debar
ardebs, bardes, beards, breads, debars, sabred, serdab
ares, arse, e

### NumPy Exercises

For the following exercises, be sure to print the desired output. You will not receive credit for problems that do not print the desired output.

Some of these exercises will require the use of functions in numpy that may not have been covered in class. Look up documentation on how to use them. I always recommend checking the official reference at https://numpy.org/doc/stable/reference/index.html 

In [8]:
import numpy as np
rng = np.random.default_rng(seed = 1)

#### Exercise NP.1:

Task: Create an array `b` of 10 random integers selected between 0-99

Desired output: `[47 51 75 95  3 14 82 94 24 31]` of course yours might be different

In [9]:
b = np.array(np.random.randint(0,100,size = 10))

In [10]:
print(b)

[83 97  4 50 56 36 80 31 50 89]


#### NP.1b:

Task: reverse the elements in `b`. Hint: Try slicing the array, but backwards

In [11]:
print(b[::-1])

[89 50 31 80 36 56 50  4 97 83]


#### NP.2a:

Task: Create an array `c` of 1000 random values selected from a normal distribution centered at 100 with sd = 15, rounded to 1 decimal place. Print only the first 10 values.

Desired output: `[ 92.1  83.9 113.   65.5 126.2  88.6 104.8  96.3 121.9  69.1]` of course your values may be different

In [12]:
c = np.random.normal(100,15,1000)
c = np.round(c,1)
print(c[0:10])

[113.5 101.1 111.6  79.2 102.4 105.3 103.4  94.1  82.4 106. ]


#### NP.2b:

Perform a Shapiro-Wilk test to see if the values in c come from a normal distribution. Report the p-value and appropriate conclusion.

Look up `scipy.stats.shapiro` for usage and details.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html

In [13]:
from scipy import stats
shapiro_test = stats.shapiro(c)
print(shapiro_test)

ShapiroResult(statistic=np.float64(0.998687612384179), pvalue=np.float64(0.6802058504592416))


A test statistic of 0.9985 is really high meaning the results have a high likelyhood of being normal. The p-value of 0.576 is not lower than 5% meaning there is no unusual behavior, thus the results are considered normal.   

#### NP.2c:

Identify and print the values in `c` that are more than 3 standard deviations from the mean of `c`. Report the proportion of values that are more than 3 sd from the mean.

Desired output: `[ 54.1 ... 148.3 ]`

`0.32 of the values are beyond 3 sd from the mean.`

In [14]:
gt3 = 0
for i in c:
    if i < 55 or i > 145:
        print(i)
        gt3 += 1

print(gt3/len(c))

51.3
146.8
49.0
145.8
0.004


#### NP.3:

Task: Make a 3x3 identity matrix called `I3`

Desired output: 

~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
~~~

In [15]:
I3 = np.identity(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### NP.4a:

Task: Make a 10x10 array of values 1 to 100. Call it X

Desired output: 

~~~
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
 ~~~

In [16]:
X = np.array(range(1,101,1))
X = X.reshape(10, 10)  # equivalent 'manual' creation
print(X)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


#### NP.4b:

Task: Make a copy of X, call it Y (1 line). Replace all values in Y that are not squares with 0 (1 line). see `numpy.isin()`

Desired output: 

~~~
[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
...
 [  0   0   0   0   0   0   0   0   0 100]]
 ~~~

In [17]:
Y = X.copy()
print(Y * np.isin(Y, [1,4,9,16,25,36,49,64,81,100]).astype(int))

[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
 [  0   0   0   0   0  36   0   0   0   0]
 [  0   0   0   0   0   0   0   0  49   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  64   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 81   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 100]]


#### NP.5:

Task: Use `np.tile()` to tile a 2x2 diagonal matrix of integers to make a checkerboard pattern. Call the matrix `checkers`

Desired output: 

~~~
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
 ~~~

In [18]:
checkers = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(checkers)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### NP.6:

Task: convert the values in `f_temp` from Farenheit to celsius. The conversion is subtract 32, then multiply by 5/9. Round to 1 decimal place.

Desired output: 

~~~
[[21.1 21.7 22.2 22.8 23.3 23.9]
 ...
 [34.4 35.  35.6 36.1 36.7 37.2]]
~~~

In [19]:
# do not modify
f_temp  = np.arange(70,100).reshape((5,6))

In [20]:
c_temp = ((f_temp - 32) * 5/9).round(1)
print(c_temp)

[[21.1 21.7 22.2 22.8 23.3 23.9]
 [24.4 25.  25.6 26.1 26.7 27.2]
 [27.8 28.3 28.9 29.4 30.  30.6]
 [31.1 31.7 32.2 32.8 33.3 33.9]
 [34.4 35.  35.6 36.1 36.7 37.2]]


#### NP.7:

Task: Convert values in the matrix `x` into z-scores by column, call it matrix `z`. That is: each column should have a mean of 0 and std of 1. (subtract the column mean, and divide by the column std). (not required, but see if you can do this in one line)

Print the column means and column std to show that they have been standardized.

Desired output: 

~~~
[[ 0.41148428  1.04307072 -1.43031951]
 [-0.34069129 -1.14825432 -0.77270135]
...
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]
 
[-1.16573418e-16  7.77156117e-17  1.44328993e-16]
[1. 1. 1.]
~~~

In [21]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 30).reshape(10,3)

In [22]:
z = (x - x.mean(axis=0)) / x.std(axis=0)
print(z)

[[ 0.41148428  1.04307072 -1.43031951]
 [-0.34069129 -1.14825432 -0.77270135]
 [-1.00437562 -1.26512499  0.46033272]
 [ 1.34064235  1.36446505  0.50143385]
 [-1.13711249  0.92620005  1.85777132]
 [ 1.07516861 -1.38199565  0.87134407]
 [ 0.19025617 -0.85607765  0.13152363]
 [ 1.38488797  0.60480571 -0.77270135]
 [-1.53532308  0.42949971 -1.34811724]
 [-0.38493691  0.28341137  0.50143385]]


#### NP.8:

Task: Convert values in the matrix `x` into scaled values from 0 to 10. That is take each column and scale values linearly so that the largest value is 10, and the smallest value in the column is 0. Round results to 2 decimal places. Call the result `y`

(Not required, but see if you can do the calculations in one line.)

Desired output: 

~~~
[[0.67 0.88 0.  ]
 [0.41 0.09 0.2 ]
 ...
 [0.   0.66 0.02]
 [0.39 0.61 0.59]]
 ~~~

In [23]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 30).reshape(10,3)

In [24]:
y = x / x.max(axis=0) * 10
y = np.round(y, 2)
print(y)

[[ 7.76  8.83  1.3 ]
 [ 6.02  0.85  3.04]
 [ 4.49  0.43  6.3 ]
 [ 9.9  10.    6.41]
 [ 4.18  8.4  10.  ]
 [ 9.29  0.    7.39]
 [ 7.24  1.91  5.43]
 [10.    7.23  3.04]
 [ 3.27  6.6   1.52]
 [ 5.92  6.06  6.41]]


#### NP.9:

Task: Replace all NaN values in the matrix `x` with 0.

Desired output: 

~~~
[[76. 83. 12.]
 [59.  8.  0.]
 [44.  0. 58.]
 [ 0. 94. 59.]]
~~~

In [25]:
# do not modify
rng = np.random.default_rng(seed = 100)
x = rng.integers(0, 100, size = 12).reshape(4,3).astype('float')
row = np.array([1, 2, 3])
col = np.array([2, 1, 0])
x[row, col] = np.nan
print(x)

[[76. 83. 12.]
 [59.  8. nan]
 [44. nan 58.]
 [nan 94. 59.]]


In [26]:
x[np.isnan(x)] = 0
print(x)    

[[76. 83. 12.]
 [59.  8.  0.]
 [44.  0. 58.]
 [ 0. 94. 59.]]
